export interface Database {
  public: {
    Tables: {
      messages: {
        Row: {
          id: string;
          user_id: string;
          platform: string;
          external_id?: string;
          thread_id?: string;
          contact_id?: string;
          sender_name?: string;
          sender_handle?: string;
          sender_email?: string;
          recipient_name?: string;
          recipient_handle?: string;
          recipient_email?: string;
          subject?: string;
          body: string;
          message_type: string;
          timestamp: string;
          is_read: boolean;
          is_archived: boolean;
          is_flagged: boolean;
          status: string;
          priority: string;
          attachments: any[];
          metadata: Record<string, any>;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          platform: string;
          external_id?: string;
          thread_id?: string;
          contact_id?: string;
          sender_name?: string;
          sender_handle?: string;
          sender_email?: string;
          recipient_name?: string;
          recipient_handle?: string;
          recipient_email?: string;
          subject?: string;
          body: string;
          message_type?: string;
          timestamp?: string;
          is_read?: boolean;
          is_archived?: boolean;
          is_flagged?: boolean;
          status?: string;
          priority?: string;
          attachments?: any[];
          metadata?: Record<string, any>;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          platform?: string;
          external_id?: string;
          thread_id?: string;
          contact_id?: string;
          sender_name?: string;
          sender_handle?: string;
          sender_email?: string;
          recipient_name?: string;
          recipient_handle?: string;
          recipient_email?: string;
          subject?: string;
          body?: string;
          message_type?: string;
          timestamp?: string;
          is_read?: boolean;
          is_archived?: boolean;
          is_flagged?: boolean;
          status?: string;
          priority?: string;
          attachments?: any[];
          metadata?: Record<string, any>;
          created_at?: string;
          updated_at?: string;
        };
      };
      contacts: {
        Row: {
          id: string;
          user_id: string;
          full_name?: string;
          first_name?: string;
          last_name?: string;
          email?: string;
          phone?: string;
          handle?: string;
          platform?: string;
          profile_image?: string;
          bio?: string;
          location?: string;
          website?: string;
          company?: string;
          job_title?: string;
          follower_count: number;
          engagement_rate: number;
          sentiment_score: number;
          tags: string[];
          custom_fields: Record<string, any>;
          enriched: boolean;
          enriched_at?: string;
          enrichment_source?: string;
          last_interaction?: string;
          interaction_count: number;
          total_value: number;
          status: string;
          source: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          full_name?: string;
          first_name?: string;
          last_name?: string;
          email?: string;
          phone?: string;
          handle?: string;
          platform?: string;
          profile_image?: string;
          bio?: string;
          location?: string;
          website?: string;
          company?: string;
          job_title?: string;
          follower_count?: number;
          engagement_rate?: number;
          sentiment_score?: number;
          tags?: string[];
          custom_fields?: Record<string, any>;
          enriched?: boolean;
          enriched_at?: string;
          enrichment_source?: string;
          last_interaction?: string;
          interaction_count?: number;
          total_value?: number;
          status?: string;
          source?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          full_name?: string;
          first_name?: string;
          last_name?: string;
          email?: string;
          phone?: string;
          handle?: string;
          platform?: string;
          profile_image?: string;
          bio?: string;
          location?: string;
          website?: string;
          company?: string;
          job_title?: string;
          follower_count?: number;
          engagement_rate?: number;
          sentiment_score?: number;
          tags?: string[];
          custom_fields?: Record<string, any>;
          enriched?: boolean;
          enriched_at?: string;
          enrichment_source?: string;
          last_interaction?: string;
          interaction_count?: number;
          total_value?: number;
          status?: string;
          source?: string;
          created_at?: string;
          updated_at?: string;
        };
      };
      comments: {
        Row: {
          id: string;
          user_id: string;
          platform: string;
          external_id?: string;
          post_id?: string;
          post_title?: string;
          post_url?: string;
          content: string;
          author_name?: string;
          author_handle?: string;
          author_avatar?: string;
          contact_id?: string;
          parent_comment_id?: string;
          timestamp: string;
          is_reply: boolean;
          replied: boolean;
          reply_content?: string;
          replied_at?: string;
          sentiment?: string;
          sentiment_score?: number;
          likes_count: number;
          replies_count: number;
          is_mention: boolean;
          workflow_triggered: boolean;
          workflow_id?: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          platform: string;
          external_id?: string;
          post_id?: string;
          post_title?: string;
          post_url?: string;
          content: string;
          author_name?: string;
          author_handle?: string;
          author_avatar?: string;
          contact_id?: string;
          parent_comment_id?: string;
          timestamp?: string;
          is_reply?: boolean;
          replied?: boolean;
          reply_content?: string;
          replied_at?: string;
          sentiment?: string;
          sentiment_score?: number;
          likes_count?: number;
          replies_count?: number;
          is_mention?: boolean;
          workflow_triggered?: boolean;
          workflow_id?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          platform?: string;
          external_id?: string;
          post_id?: string;
          post_title?: string;
          post_url?: string;
          content?: string;
          author_name?: string;
          author_handle?: string;
          author_avatar?: string;
          contact_id?: string;
          parent_comment_id?: string;
          timestamp?: string;
          is_reply?: boolean;
          replied?: boolean;
          reply_content?: string;
          replied_at?: string;
          sentiment?: string;
          sentiment_score?: number;
          likes_count?: number;
          replies_count?: number;
          is_mention?: boolean;
          workflow_triggered?: boolean;
          workflow_id?: string;
          created_at?: string;
        };
      };
      contact_enrichment_logs: {
        Row: {
          id: string;
          contact_id: string;
          user_id: string;
          enriched_by: string;
          enrichment_type: string;
          data_before: Record<string, any>;
          data_after: Record<string, any>;
          fields_updated: string[];
          confidence_score?: number;
          cost: number;
          status: string;
          error_message?: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          contact_id: string;
          user_id: string;
          enriched_by: string;
          enrichment_type: string;
          data_before?: Record<string, any>;
          data_after?: Record<string, any>;
          fields_updated?: string[];
          confidence_score?: number;
          cost?: number;
          status?: string;
          error_message?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          contact_id?: string;
          user_id?: string;
          enriched_by?: string;
          enrichment_type?: string;
          data_before?: Record<string, any>;
          data_after?: Record<string, any>;
          fields_updated?: string[];
          confidence_score?: number;
          cost?: number;
          status?: string;
          error_message?: string;
          created_at?: string;
        };
      };
      contact_interactions: {
        Row: {
          id: string;
          contact_id: string;
          user_id: string;
          interaction_type: string;
          platform?: string;
          title?: string;
          description?: string;
          metadata: Record<string, any>;
          timestamp: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          contact_id: string;
          user_id: string;
          interaction_type: string;
          platform?: string;
          title?: string;
          description?: string;
          metadata?: Record<string, any>;
          timestamp?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          contact_id?: string;
          user_id?: string;
          interaction_type?: string;
          platform?: string;
          title?: string;
          description?: string;
          metadata?: Record<string, any>;
          timestamp?: string;
          created_at?: string;
        };
      };
      contact_tags: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          color: string;
          description?: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          color?: string;
          description?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          color?: string;
          description?: string;
          created_at?: string;
        };
      };
    };
  };
}